chore: #1: Introduce HTML reporting
Anthony-Nolan/Atlas.Auto.Tests pull request #24
Opened 2024-02-26 14:54 UTC by GrigoriyGriban

chore: #1: Introduce HTML reporting

2024-02-26 15:41 UTC, daria-sorokina-da requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 11 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, @pchenery, and @zabeen)

___
*[`.gitignore` line 401 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nr_zKSmCQGI_DAV5UUJ:-Nr_zKSmCQGI_DAV5UUK:b-9ofjv4) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/.gitignore#L401)):*
> ```ignore
> 
> # Report file
> *.html
> ```

Could you gitignore only the html file in the TestReport folder?
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3XrE0ZwtMr8hEEzv:-Nra3XrE0ZwtMr8hEEzw:b-e7ye68) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L22)):*
> ```Smalltalk
>     };
> 
>     private static string testName = "Health Check Test";
> ```

"Health Check Tests"
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 35 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2loZ411uT5NxMVn7:-Nra2loZ411uT5NxMVn8:b-vaj6rh) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L35)):*
> ```Smalltalk
>         var test = ExtentManager.CreateMethod(testName,
>             $"Health Check Test for {clientType.Name}",
>             $"Health Check Tests for {clientType.Name}");
> ```

Do we need this description? It is the same as the test name
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 37 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3f99-gE1dgEtVCDC:-Nra3f99-gE1dgEtVCDD:btelyyy) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L37)):*
> ```Smalltalk
>             $"Health Check Tests for {clientType.Name}");
> 
>         test.Log(Status.Info, $"Start Health Check Test for client type: {clientType.Name}");
> ```

Started health check for client type {clientType.Name}...
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 40 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3jns2da08mbbS36b:-Nra3jns2da08mbbS36c:b-t7dh0q) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L40)):*
> ```Smalltalk
>         var client = Provider.ResolveServiceOrThrow(clientType) as HttpFunctionClient;
>         var result = await client!.HealthCheck();
>         test.Log(Status.Info, $"Health Check Test for client type: {clientType.Name} result: {result}");
> ```

Result of health check for client type {clientType.Name}: {result}
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2V4T5upKAMmgyTnj:-Nra2V4T5upKAMmgyTnk:b-hz4zsi) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L14)):*
> ```Smalltalk
>         private static readonly object syncLock = new object();
> 
>         // creates a parent test
> ```

// Creates a parent node in the report for the test fixture
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2OqiClWyB5eq40M6:-Nra2OqiClWyB5eq40M7:b-diu5kv) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L15)):*
> ```Smalltalk
> 
>         // creates a parent test
>         public static ExtentTest CreateTest(string testName, string description = null)
> ```

CreateForFixture
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 25 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2a3l-pyMZoqPTV9p:-Nra2a3l-pyMZoqPTV9q:b-6an05m) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L25)):*
> ```Smalltalk
>         }
> 
>         // creates a node
> ```

// Creates a node in the report for the individual test
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 28 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2RT44H9Su1bHg6fG:-Nra2RT44H9Su1bHg6fH:bb39ysa) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L28)):*
> ```Smalltalk
>         // node is added to the parent using the parentName
>         // if the parent is not available, it will be created
>         public static ExtentTest CreateMethod(string parentName, string testName, string description = null)
> ```

CreateForTest
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra1hxvBAw5x_FXB5Um:-Nra1hxvBAw5x_FXB5Un:b1hofod) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentService.cs#L10)):*
> ```Smalltalk
>     {
>         private const string folderName = @"TestReport";
>         private static readonly Lazy<ExtentReports> lazy = new Lazy<ExtentReports>(() => new ExtentReports());
> ```

lazy -> expentReportsLazy
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 39 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2-9CA3BxN4sIAgQw:-Nra2-9CA3BxN4sIAgQx:byvwx46) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentService.cs#L39)):*
> ```Smalltalk
>                 Directory.CreateDirectory(path);
>             }
>             return path + @"\index.html";
> ```

Can we add this file name using Path.Combine so that we don't hardcode the back slash? 


<!-- Sent from Reviewable.io -->

2024-02-26 15:55 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 4 of 8 files reviewed, 11 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`.gitignore` line 401 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nr_zKSmCQGI_DAV5UUJ:-Nra79rA16_nicd4i8iL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/.gitignore#L401)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Could you gitignore only the html file in the TestReport folder?
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3XrE0ZwtMr8hEEzv:-Nra4qRu9gv5kXQyM0vp:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L22)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

"Health Check Tests"
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 35 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2loZ411uT5NxMVn7:-Nra4r7M6tMKWXF9tGFh:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L35)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we need this description? It is the same as the test name
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 37 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3f99-gE1dgEtVCDC:-Nra4yEBCtoMjyzF_dVi:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L37)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Started health check for client type {clientType.Name}...
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 40 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra3jns2da08mbbS36b:-Nra5-n31mGMNJIsKJYo:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L40)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Result of health check for client type {clientType.Name}: {result}
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2V4T5upKAMmgyTnj:-Nra5CHF2VbRDLwa3883:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L14)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

// Creates a parent node in the report for the test fixture
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2OqiClWyB5eq40M6:-Nra5Cs48EwlEgJjlgfH:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

CreateForFixture
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 25 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2a3l-pyMZoqPTV9p:-Nra5lV5-LcTZHQFh8Bf:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L25)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

// Creates a node in the report for the individual test
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 28 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2RT44H9Su1bHg6fG:-Nra5LYA6x4u9vqhkJTb:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L28)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

CreateForTest
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra1hxvBAw5x_FXB5Um:-Nra5QJNAQRbRZ4GOtvC:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentService.cs#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

lazy -> expentReportsLazy
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 39 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra2-9CA3BxN4sIAgQw:-Nra5cspAvrV5hR-sexI:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7ddabb7efc8049adfc53a7a4fe31e912c03b6718/Atlas.Auto.Utils/Reporting/ExtentService.cs#L39)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Can we add this file name using Path.Combine so that we don't hardcode the back slash?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 15:57 UTC, daria-sorokina-da requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @GrigoriyGriban, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 26 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra7YwW-ZwR1ivFP7l0:-Nra7YwW-ZwR1ivFP7l1:bwkcvtx) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/11d7f5de21e2405fdc093e7bfcc253e59763bf66/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L26)):*
> ```Smalltalk
> 
>         // Creates a node in the report for the individual test
>         // node is added to the parent using the parentName
> ```

Please delete all these additional comment lines


<!-- Sent from Reviewable.io -->

2024-02-26 15:58 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 26 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nra7YwW-ZwR1ivFP7l0:-Nra7sXI54WeDFLl-1QN:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/11d7f5de21e2405fdc093e7bfcc253e59763bf66/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L26)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please delete all these additional comment lines
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 16:54 UTC, daria-sorokina-da approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alikhanmda, @pchenery, and @zabeen)



<!-- Sent from Reviewable.io -->

2024-02-27 11:59 UTC, zabeen requested changes
> Reviewed 6 of 8 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 11 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 22 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreAbxq0U6dT__nRAXr:-NreAbxq0U6dT__nRAXs:b-rfbwyg) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L22)):*
> ```Smalltalk
>     };
> 
>     private static string testName = "Health Check Tests";
> ```

please rename to` testFixtureName` to make it clearer



_Code quote:_
```Smalltalk
testName
```
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 26 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreLPbl6fdISK8eUVhT:-NreLPbl6fdISK8eUVhU:b-pmdkqp) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L26)):*
> ```Smalltalk
>     public HealthCheckTests()
>     {
>         ExtentTest = ExtentManager.CreateForFixture(testName);
> ```

could this be moved to the [OneTimeSetUp] method within the `TestBase` parent class - or the test base constructor? The test fixture name can be passed into the `TestBase` constructor.

AFAIK, we don't use `ExtentClass` within the child class - it could even be made private in`TestBase`?

That would minimise boilerplate code in child class.



_Code quote:_
```Smalltalk
ExtentTest = ExtentManager.CreateForFixture(testName);
```
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 6 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NrePEdn2yRlDNY5sjla:-NrePEdn2yRlDNY5sjlb:b8olugk) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L6)):*
> ```Smalltalk
> namespace Atlas.Auto.Tests.Tests
> {
>     public class TestBase
> ```

could make class `abstract`



_Code quote:_
```Smalltalk
public class 
```
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 8 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreMffm34jqGu83HlGt:-NreMffm34jqGu83HlGu:bwnd9b) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L8)):*
> ```Smalltalk
>     public class TestBase
>     {
>         public static ExtentTest ExtentTest;
> ```

as above, could change to `private` if it's not going to be referenced by child test fixture, else to `protected`.



_Code quote:_
```Smalltalk
public
```
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 9 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreMdqd4HGJR5Y8wCFA:-NreMdqd4HGJR5Y8wCFB:b-dj3umg) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L9)):*
> ```Smalltalk
>     {
>         public static ExtentTest ExtentTest;
>         public IServiceProvider Provider;
> ```

change to `protected`



_Code quote:_
```Smalltalk
public
```
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 18 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreQiQo5gAOk0kJQf8p:-NreQiQo5gAOk0kJQf8q:bn28kz3) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L18)):*
> ```Smalltalk
>         protected TestBase()
>         {
>         }
> ```

redundant empty constructors can be removed



_Code quote:_
```Smalltalk
        static TestBase()
        {

        }

        protected TestBase()
        {
        }
```
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 52 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NrePP_71jOuaLaU-RNr:-NrePP_71jOuaLaU-RNs:bmn5adv) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L52)):*
> ```Smalltalk
>         {
>             Uninitialize();
>         }
> ```

The base class is not doing anything during setup/teardown - so we could remove all this, and just let the child test fixture set up their own [SetUp]/[TearDown] as needed.

If in future, base class needs to run its own setup/teardown, NUnit allows parent/child to both use this attribute, and executes both, so it should be fine.



_Code quote:_
```Smalltalk
        /// <summary>
        /// This should be overloaded in derived classes.
        /// Initialization of state before each test case runs. Equals [SetUp]
        /// </summary>
        protected virtual void Initialize()
        {
        }

        /// <summary>
        /// This should be overloaded in derived classes.
        /// Uninitialization of state before each test case runs. Equals [TearDown]
        /// </summary>
        protected virtual void Uninitialize()
        {
        }

        [SetUp]
        public void InitializeBase()
        {
            Initialize();
        }

        [TearDown]
        public void UninitializeBase()
        {
            Uninitialize();
        }
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 5 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreCzFH-dlu16kldL8j:-NreCzFH-dlu16kldL8k:bnz64wr) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L5)):*
> ```Smalltalk
> namespace Atlas.Auto.Utils.Reporting
> {
>     public static class ExtentManager
> ```

General comment: it may be preferable to use `ConcurrentDictionary`/`TryAdd` in this class instead of `Dictionary`/lock
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 15 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreJXDPEiUhFm62F9sP:-NreJXDPEiUhFm62F9sQ:b-mhcrvl) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L15)):*
> ```Smalltalk
> 
>         // Creates a parent node in the report for the test fixture
>         public static ExtentTest CreateForFixture(string testName, string description = null)
> ```

As above, please rename to `tesFixtureName`



_Code quote:_
```Smalltalk
testName
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 10 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreHYAQ52VHWcEC3DX7:-NreHYAQ52VHWcEC3DX8:b-q0pgib) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentService.cs#L10)):*
> ```Smalltalk
>     {
>         private const string folderName = @"TestReport";
>         private static readonly Lazy<ExtentReports> expentReportsLazy = new Lazy<ExtentReports>(() => new ExtentReports());
> ```

typo: `extent...`



_Code quote:_
```Smalltalk
expentReportsLazy
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 12 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreHRd9BkIFxBmhOGAE:-NreHRd9BkIFxBmhOGAF:b-qi7qob) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentService.cs#L12)):*
> ```Smalltalk
>         private static readonly Lazy<ExtentReports> expentReportsLazy = new Lazy<ExtentReports>(() => new ExtentReports());
> 
>         public static ExtentReports Instance { get { return expentReportsLazy.Value; } }
> ```

can use expression body: `public static ExtentReports Instance => expentReportsLazy.Value;`



_Code quote:_
```Smalltalk
public static ExtentReports Instance { get { return expentReportsLazy.Value; } }
```


<!-- Sent from Reviewable.io -->

2024-02-27 12:00 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 11 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 26 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreLPbl6fdISK8eUVhT:-NreR-2v2OSFCCa_RFaR:b-z0j964) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L26)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

could this be moved to the [OneTimeSetUp] method within the `TestBase` parent class - or the test base constructor? The test fixture name can be passed into the `TestBase` constructor.

AFAIK, we don't use `ExtentClass` within the child class - it could even be made private in`TestBase`?

That would minimise boilerplate code in child class.
</blockquote></details>

Correction: AFAIK, we don't use `ExtentTest` within the child class...


<!-- Sent from Reviewable.io -->

2024-02-27 12:02 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 12 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 8 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreRJK8A8dKfJjw3l_O:-NreRJK8A8dKfJjw3l_P:b-3nej6g) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L8)):*
> ```Smalltalk
>     public class TestBase
>     {
>         public static ExtentTest ExtentTest;
> ```

suggest rename to `ExtentTestForFixture`



_Code quote:_
```Smalltalk
ExtentTest;
```


<!-- Sent from Reviewable.io -->

2024-02-27 12:32 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 13 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 10 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreXssP57opzAbPw-5U:-NreXssP57opzAbPw-5V:b9ig2yu) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L10)):*
> ```Smalltalk
>         private static Dictionary<string, ExtentTest> childTestMap = new Dictionary<string, ExtentTest>();
>         private static ThreadLocal<ExtentTest> parentTest = new ThreadLocal<ExtentTest>();
>         private static ThreadLocal<ExtentTest> childTest = new ThreadLocal<ExtentTest>();
> ```

I do not think these need to be fields, as we are saving to dictionary, and calling parent/child from dictionary when needed. I think they can be local variables within scope of the methods below.



_Code quote:_
```Smalltalk
        private static ThreadLocal<ExtentTest> parentTest = new ThreadLocal<ExtentTest>();
        private static ThreadLocal<ExtentTest> childTest = new ThreadLocal<ExtentTest>();
```


<!-- Sent from Reviewable.io -->

2024-02-27 14:27 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 4 of 8 files reviewed, 12 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 22 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreAbxq0U6dT__nRAXr:-NrehaUR7-WbAJ7pK4si:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L22)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please rename to` testFixtureName` to make it clearer
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/HealthCheckTests.cs` line 26 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreLPbl6fdISK8eUVhT:-NreieeA4h1JX11LelMS:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/HealthCheckTests.cs#L26)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Correction: AFAIK, we don't use `ExtentTest` within the child class...
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 6 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NrePEdn2yRlDNY5sjla:-NreoBqF1Re0GQ3axhp4:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L6)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

could make class `abstract`
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 8 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreMffm34jqGu83HlGt:-NreoFqh3HNr2TFgQJQZ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L8)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

as above, could change to `private` if it's not going to be referenced by child test fixture, else to `protected`.
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 8 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreRJK8A8dKfJjw3l_O:-NreoLHMBtCgdk-KfERR:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L8)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

suggest rename to `ExtentTestForFixture`
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 9 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreMdqd4HGJR5Y8wCFA:-NreoOVL3eO-hz7ypFGV:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

change to `protected`
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 18 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreQiQo5gAOk0kJQf8p:-NreoSZd2nDZc39Dxn9_:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L18)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

redundant empty constructors can be removed
</blockquote></details>

Done.
___
*[`Atlas.Auto.Tests/Tests/TestBase.cs` line 52 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NrePP_71jOuaLaU-RNr:-NrepE8ND2-XokCJQ_BG:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Tests/Tests/TestBase.cs#L52)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

The base class is not doing anything during setup/teardown - so we could remove all this, and just let the child test fixture set up their own [SetUp]/[TearDown] as needed.

If in future, base class needs to run its own setup/teardown, NUnit allows parent/child to both use this attribute, and executes both, so it should be fine.
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 5 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreCzFH-dlu16kldL8j:-Nrerr8I9IU5Ofrv1bfu:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L5)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

General comment: it may be preferable to use `ConcurrentDictionary`/`TryAdd` in this class instead of `Dictionary`/lock
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 10 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreXssP57opzAbPw-5U:-NretQIQ97uHD8oduPkL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L10)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I do not think these need to be fields, as we are saving to dictionary, and calling parent/child from dictionary when needed. I think they can be local variables within scope of the methods below.
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 15 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreJXDPEiUhFm62F9sP:-Nrer2nzBk7TBLJf6-eQ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L15)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

As above, please rename to `tesFixtureName`
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentService.cs` line 12 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreHRd9BkIFxBmhOGAE:-NrehTCw0CeBNtRYwyFW:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/97a20ce182b25eb9a7f7a9140577c18fb69a6f53/Atlas.Auto.Utils/Reporting/ExtentService.cs#L12)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

can use expression body: `public static ExtentReports Instance => expentReportsLazy.Value;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 14:39 UTC, zabeen requested changes
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 4 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 17 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nreyyip1cCNY6_P2g3f:-Nreyyip1cCNY6_P2g3g:bxq0y6f) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7b95ec742596d979dc597da93273f278d5cd9eb2/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L17)):*
> ```Smalltalk
>             parentTest.Value = ExtentService.Instance.CreateTest(testFixtureName, description);
>             parentTestMap.TryAdd(testFixtureName, parentTest.Value);
>             return parentTest.Value;
> ```

Can simplify using `GetOrAdd` with factory:
```
return parentTestMap.GetOrAdd(testFixtureName, ExtentService.Instance.CreateTest(testFixtureName, description));
```



_Code quote:_
```Smalltalk
            var parentTest = new ThreadLocal<ExtentTest>();
            parentTest.Value = ExtentService.Instance.CreateTest(testFixtureName, description);
            parentTestMap.TryAdd(testFixtureName, parentTest.Value);
            return parentTest.Value;
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 36 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreyeuBCtS4_l8sAFWj:-NreyeuBCtS4_l8sAFWk:b-iio0it) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7b95ec742596d979dc597da93273f278d5cd9eb2/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L36)):*
> ```Smalltalk
>             childTest.Value = parentTest.CreateNode(testName, description);
>             childTestMap.TryAdd(testName, childTest.Value);
>             return childTest.Value;
> ```

can simplify by using `GetOrAdd` with factory:
```
var parentTest = parentTestMap.GetOrAdd(parentName, ExtentService.Instance.CreateTest(parentName));
return childTestMap.GetOrAdd(testName, parentTest.CreateNode(testName, description));
```



_Code quote:_
```Smalltalk
            ExtentTest parentTest = null;
            if (!parentTestMap.ContainsKey(parentName))
            {
                parentTest = ExtentService.Instance.CreateTest(testName);
                parentTestMap.TryAdd(parentName, parentTest);
            }
            else
            {
                parentTest = parentTestMap[parentName];
            }
            var childTest = new ThreadLocal<ExtentTest>();
            childTest.Value = parentTest.CreateNode(testName, description);
            childTestMap.TryAdd(testName, childTest.Value);
            return childTest.Value;
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 8 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf-Jm33s-BTQ2QBxcN:-Nrf-Jm33s-BTQ2QBxcO:b-pe83s1) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/86f777351c27e9522ae80af662435be22953eb38/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L8)):*
> ```Smalltalk
>     public static class ExtentManager
>     {
>         private static ConcurrentDictionary<string, ExtentTest> parentTestMap = new ConcurrentDictionary<string, ExtentTest>();
> ```

suggest rename to `testFixtureMap`



_Code quote:_
```Smalltalk
parentTestMap
```
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 19 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf-6DVAq7JFJdSeZEr:-Nrf-6DVAq7JFJdSeZEs:bqkfaae) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/86f777351c27e9522ae80af662435be22953eb38/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L19)):*
> ```Smalltalk
> 
>         // Creates a node in the report for the individual test
>         public static ExtentTest CreateForTest(string parentName, string testName, string description = null)
> ```

rename to `testFixtureName`



_Code quote:_
```Smalltalk
parentName
```


<!-- Sent from Reviewable.io -->

2024-02-27 14:45 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @alikhanmda, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 17 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nreyyip1cCNY6_P2g3f:-Nrf-wFe4zVzjBfHDdb5:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7b95ec742596d979dc597da93273f278d5cd9eb2/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Can simplify using `GetOrAdd` with factory:
```
return parentTestMap.GetOrAdd(testFixtureName, ExtentService.Instance.CreateTest(testFixtureName, description));
```
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 36 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-NreyeuBCtS4_l8sAFWj:-Nrf0bNr8CU7UDl69Od3:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7b95ec742596d979dc597da93273f278d5cd9eb2/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L36)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

can simplify by using `GetOrAdd` with factory:
```
var parentTest = parentTestMap.GetOrAdd(parentName, ExtentService.Instance.CreateTest(parentName));
return childTestMap.GetOrAdd(testName, parentTest.CreateNode(testName, description));
```
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 8 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf-Jm33s-BTQ2QBxcN:-Nrf-hWj653_338txDVh:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/86f777351c27e9522ae80af662435be22953eb38/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L8)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

suggest rename to `testFixtureMap`
</blockquote></details>

Done.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 19 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf-6DVAq7JFJdSeZEr:-Nrf00n0AG6PtS4kk8u-:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/86f777351c27e9522ae80af662435be22953eb38/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L19)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

rename to `testFixtureName`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 14:46 UTC, daria-sorokina-da approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 4 unresolved discussions (waiting on @alikhanmda, @pchenery, and @zabeen)



<!-- Sent from Reviewable.io -->

2024-02-27 14:55 UTC, zabeen approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 20 at r6](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf2VRP9OBGRjw0UFvh:-Nrf2VRP9OBGRjw0UFvi:b-2qy3w7) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ef581e968e4317041f09b5a6f850f8515ff3d7fc/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L20)):*
> ```Smalltalk
>         {
>             var parentTest = testFixtureMap.GetOrAdd(testFixtureName, ExtentService.Instance.CreateTest(testFixtureName));
>             return parentTest.CreateNode(testName, description);
> ```

I think I may have missed a commit - I take it you intentionally removed the child test map dictionary? It makes sense as it's only the test fixture/parent map that will be repeatedly referenced when creating the child nodes.


<!-- Sent from Reviewable.io -->

2024-02-27 15:09 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 20 at r6](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf2VRP9OBGRjw0UFvh:-Nrf5Sr21b-yhAYCTEGe:bkhzq6h) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ef581e968e4317041f09b5a6f850f8515ff3d7fc/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L20)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I think I may have missed a commit - I take it you intentionally removed the child test map dictionary? It makes sense as it's only the test fixture/parent map that will be repeatedly referenced when creating the child nodes.
</blockquote></details>

I've rolled back my code, because only this code generates report in correct format. 


<!-- Sent from Reviewable.io -->

2024-02-27 15:11 UTC, zabeen requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 22 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf6Vpv4IpHZvGbuyKr:-Nrf6Vpv4IpHZvGbuyKs:b-3ycxjq) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L22)):*
> ```Smalltalk
>             if (!testFixtureMap.ContainsKey(testFixtureName))
>             {
>                 parentTest = ExtentService.Instance.CreateTest(testName);
> ```

parent test being created using the `testName`, not the `testFixtureName`


<!-- Sent from Reviewable.io -->

2024-02-27 15:13 UTC, zabeen reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 20 at r6](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf2VRP9OBGRjw0UFvh:-Nrf6qRy8eFPw5o3gTU4:b6s4cc7) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ef581e968e4317041f09b5a6f850f8515ff3d7fc/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L20)):*
<details><summary><i>Previously, GrigoriyGriban (Grigoriy Griban) wrote…</i></summary><blockquote>

I've rolled back my code, because only this code generates report in correct format.
</blockquote></details>

The rolled back code is functionally identical to shorter version - only difference is the line I commented 


<!-- Sent from Reviewable.io -->

2024-02-27 15:14 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 22 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf6Vpv4IpHZvGbuyKr:-Nrf71e78rfnIVXw33iq:bwgf1ob) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L22)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

parent test being created using the `testName`, not the `testFixtureName`
</blockquote></details>

this is correct, `testFixtureName` is parent Node, 'testName' is child Node in Report tree.


<!-- Sent from Reviewable.io -->

2024-02-27 15:14 UTC, daria-sorokina-da requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 3 unresolved discussions (waiting on @alikhanmda, @GrigoriyGriban, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 19 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf7GG48To0L4mENpWj:-Nrf7GG48To0L4mENpWk:b-xsb0mx) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L19)):*
> ```Smalltalk
>         public static ExtentTest CreateForTest(string testFixtureName, string testName, string description = null)
>         {
>             ExtentTest parentTest = null;
> ```

parentTest -> testFixture


<!-- Sent from Reviewable.io -->

2024-02-27 15:16 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 20 at r6](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf2VRP9OBGRjw0UFvh:-Nrf7STH1uSrPPSJFeJp:bfymik2) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ef581e968e4317041f09b5a6f850f8515ff3d7fc/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L20)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

The rolled back code is functionally identical to shorter version - only difference is the line I commented
</blockquote></details>

This is correct code.
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 19 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf7GG48To0L4mENpWj:-Nrf7rKE0EOn7e0cSsmz:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L19)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

parentTest -> testFixture
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 15:30 UTC, zabeen requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 3 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, @GrigoriyGriban, and @pchenery)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 20 at r6](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf2VRP9OBGRjw0UFvh:-NrfAWi356zw4nZwUZD4:bf6kyxv) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/ef581e968e4317041f09b5a6f850f8515ff3d7fc/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L20)):*
<details><summary><i>Previously, GrigoriyGriban (Grigoriy Griban) wrote…</i></summary><blockquote>

This is correct code.
</blockquote></details>

ok, I think it's something to do with timing - let's merge with this version, and I will experiment more when I pick up the donor import logging ticket
___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 22 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf6Vpv4IpHZvGbuyKr:-Nrf8ny5ElJ4etJfyxD2:b-bhponw) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L22)):*
<details><summary><i>Previously, GrigoriyGriban (Grigoriy Griban) wrote…</i></summary><blockquote>

this is correct, `testFixtureName` is parent Node, 'testName' is child Node in Report tree.
</blockquote></details>

shouldn't it be: `testFixture = ExtentService.Instance.CreateTest(testFixtureName);`?


<!-- Sent from Reviewable.io -->

2024-02-27 15:34 UTC, daria-sorokina-da requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @GrigoriyGriban, and @pchenery)



<!-- Sent from Reviewable.io -->

2024-02-27 15:35 UTC, GrigoriyGriban reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @alikhanmda, @daria-sorokina-da, @pchenery, and @zabeen)

___
*[`Atlas.Auto.Utils/Reporting/ExtentManager.cs` line 22 at r7](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24#-Nrf6Vpv4IpHZvGbuyKr:-NrfC4Qy67PdNATsv9Eh:b-nd8zwx) ([raw file](https://github.com/Anthony-Nolan/Atlas.Auto.Tests/blob/7de0dce7316b6de38ba5663076ef58d35c72c4a6/Atlas.Auto.Utils/Reporting/ExtentManager.cs#L22)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

shouldn't it be: `testFixture = ExtentService.Instance.CreateTest(testFixtureName);`?
</blockquote></details>

yes, it should be `testFixtureName`


<!-- Sent from Reviewable.io -->

2024-02-27 15:37 UTC, merged

2024-02-27 15:37 UTC, daria-sorokina-da reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas.Auto.Tests/24)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->